import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { KeyRound, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SiteLogoStacked } from "@/components/SiteLogo";

export default function MemberResetPassword() {
  const [location, navigate] = useLocation();
  const token = useMemo(() => new URLSearchParams(location.split("?")[1] || "").get("token") || "", [location]);
  const [valid, setValid] = useState<boolean | null>(null); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch(`/api/member/auth/reset-password?token=${encodeURIComponent(token)}`).then((r)=>r.json().then((data)=>({ok:r.ok,data}))).then(({ok,data})=>{setValid(ok); if(!ok)setError(data.error);}).catch(()=>{setValid(false);setError("We could not verify this link.");}); }, [token]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); if(password.length<8){setError("Password must be at least 8 characters.");return;} if(password!==confirm){setError("Passwords do not match.");return;} setLoading(true); try { const res=await fetch("/api/member/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password,confirm_password:confirm})}); const data=await res.json(); if(!res.ok){setError(data.error);return;} navigate(data.redirect||"/portal"); } finally {setLoading(false);} };
  return <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center p-4"><div className="w-full max-w-sm"><div className="flex flex-col items-center mb-8"><SiteLogoStacked size="lg"/></div><div className="bg-[#111] border border-white/10 rounded-2xl p-8"><div className="flex items-center justify-center w-10 h-10 rounded-full bg-brand-yellow/10 mx-auto mb-6"><KeyRound className="w-5 h-5 text-brand-yellow"/></div>{valid===null?<div className="flex justify-center text-gray-400"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Verifying secure link…</div>:!valid?<div className="text-center"><h1 className="font-bold text-white">Reset link unavailable</h1><p className="mt-3 text-sm text-red-300">{error}</p><a href="/member-forgot-password" className="mt-5 inline-block text-brand-yellow text-sm">Request another link</a></div>:<><h1 className="text-center font-bold text-white">Choose a new password</h1><form onSubmit={submit} className="mt-6 space-y-4"><div><Label className="text-gray-400">New password</Label><Input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="new-password" className="mt-1 bg-white/5 border-white/10 text-white"/></div><div><Label className="text-gray-400">Confirm new password</Label><Input type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} autoComplete="new-password" className="mt-1 bg-white/5 border-white/10 text-white"/></div>{error&&<p className="text-sm text-red-300">{error}</p>}<Button type="submit" disabled={loading} className="w-full bg-primary font-bold text-primary-foreground">{loading?"Saving…":"Save password and enter portal"}</Button></form></>}</div></div></div>;
}
