import { SiteLogo } from "@/components/SiteLogo";
import { Check, Loader2, LogOut, Printer } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

const signals = ["Mentions an adult child who rarely calls.", "Talks about family estrangement.", "Says he misses his grandchildren.", "Expresses regret about fatherhood.", "Mentions unresolved conflict with a son or daughter.", "Says he does not know how to apologize.", "Shares that he has been praying for restoration.", "Appears successful publicly but carries private family pain.", "Wants help but is afraid of making the situation worse."];
const channels = ["Personal phone contacts", "Facebook friends and groups", "LinkedIn connections", "Church and ministry contacts", "Past coaching contacts", "Fathers encountered through community relationships", "Podcast guests and listeners", "Veterans and men’s organizations", "Referrals from counselors, pastors, and ministry leaders"];
const targets = ["Identify 10 relevant fathers or referral partners.", "Send 5 personal relationship-first messages.", "Start 3 genuine conversations.", "Invite 1 qualified father to review Papa Life.", "Follow up with 2 previous conversations.", "Record what was learned from the conversations."];
const flow = [["Notice", "Recognize a statement or situation connected to father-adult-child distance."], ["Connect", "Begin as a person, not as a salesperson."], ["Listen", "Understand the father’s experience before offering advice."], ["Clarify", "Help him name what he wants to change."], ["Give Hope", "Explain that fatherhood is not finished and personal change remains possible."], ["Invite", "Offer Papa Life as a next step without pressure."]];
const questions = ["What has been the hardest part of being a father to adult children?", "How has your relationship with your son or daughter changed over the years?", "Is there a conversation you wish you could have again?", "What do you wish your adult child understood about you?", "What would a healthier relationship look like to you?", "What have you already tried?", "Would you be open to a resource created specifically for fathers walking through this?"];
const messages = [
  ["Personal Check-in", "Brother, I have been talking with fathers about the changes that happen when our children become adults. A lot of men carry distance, regret, or questions they do not talk about publicly. How has that season of fatherhood been for you?"],
  ["Direct but Respectful", "I created Papa Life for fathers who love their adult children but may be dealing with silence, tension, or distance. I am reaching out personally because this is not something men should have to carry alone. Does any part of that connect with your experience?"],
  ["Referral Partner", "I am building Papa Life to help fathers of adult children move from distance and defensiveness toward humility, safer communication, and the possibility of reconnection. Do you know a father who may be carrying this privately and would benefit from knowing he is not alone?"],
  ["Social Media Response", "Thank you for sharing that. Many fathers experience this but rarely speak about it. Fatherhood does not end when our children become adults. The next season may require a different kind of listening, leadership, and presence."],
  ["Follow-up", "I wanted to follow up on what you shared about your relationship with your adult child. I have not forgotten it. There is no pressure from me—I simply wanted you to know that practical help and a community of fathers are available when you are ready."],
];
const strongFit = ["He recognizes there is a problem.", "He wants the relationship to improve.", "He is willing to consider his role.", "He is open to learning.", "He understands that change takes time.", "He is not demanding a guaranteed response from his adult child."];
const notReady = ["He only wants help proving the child is wrong.", "He insists the adult child must change first.", "He wants a manipulation tactic.", "He refuses all personal responsibility.", "He expects an immediate reconciliation guarantee."];
const reflection = ["Who did I listen to today?", "What pain or need did I hear?", "Did I understand before offering a solution?", "Did I speak with hope and honesty?", "Who needs a follow-up?", "What did today’s conversations teach me about fathers?", "Did I treat people as people rather than prospects?"];

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="break-inside-avoid rounded-xl border border-[#17231c]/15 bg-white p-6 shadow-sm print:rounded-none print:border-[#999] print:shadow-none"><h2 className="text-2xl font-extrabold text-[#145b35]">{title}</h2><div className="mt-4">{children}</div></section>; }
function Checklist({ items }: { items: string[] }) { return <ul className="space-y-3">{items.map(x => <li key={x} className="flex gap-3"><span className="mt-0.5 inline-flex h-5 w-5 shrink-0 rounded border border-[#17231c]/40 print:bg-white" aria-hidden="true"/><span>{x}</span></li>)}</ul>; }

export default function PapaLifeOutreach() {
  const [, navigate] = useLocation();
  const [authorized, setAuthorized] = useState(false);
  useEffect(() => { fetch("/api/auth/me", { credentials: "include" }).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(d => d.ok ? setAuthorized(true) : navigate("/login?returnTo=/admin/papa-life-outreach")).catch(() => navigate("/login?returnTo=/admin/papa-life-outreach")); }, []);
  if (!authorized) return <div className="flex min-h-screen items-center justify-center bg-[#17231c] text-white"><Loader2 className="h-8 w-8 animate-spin"/><span className="sr-only">Checking administrator access</span></div>;
  const logout = async () => { await fetch("/api/auth/logout", { method: "POST" }); navigate("/login"); };
  return <div className="min-h-screen bg-[#f8f0db] text-[#17231c] print:bg-white">
    <style>{`@media print { @page { margin: .55in; } nav,.no-print { display:none!important; } body { background:white!important; } .print-grid-one { grid-template-columns:1fr!important; } section { page-break-inside:avoid; } input,textarea { border:1px solid #777!important; } }`}</style>
    <nav className="bg-[#17231c] text-white"><div className="container flex min-h-20 items-center justify-between gap-4 py-3"><a href="/"><SiteLogo size="md" /></a><div className="flex gap-3"><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-md bg-[#f2c230] px-4 py-3 font-extrabold text-[#17231c]"><Printer className="h-4 w-4"/> Print Daily Blueprint</button><button onClick={logout} aria-label="Sign out" className="rounded-md border border-white/30 p-3"><LogOut className="h-4 w-4"/></button></div></div></nav>
    <header className="bg-[#145b35] py-12 text-white print:bg-white print:py-4 print:text-black"><div className="container"><p className="text-sm font-black uppercase tracking-[.18em] text-[#f2c230] print:text-black">Owner resource · Private</p><h1 className="mt-3 text-4xl font-extrabold md:text-5xl">Papa Life Daily Outreach Blueprint</h1><p className="mt-4 max-w-3xl text-lg text-white/80 print:text-black">A relationship-first daily guide for finding, listening to, and inviting fathers of adult children—without treating people as quotas.</p></div></header>
    <main className="container grid gap-6 py-10 print:px-0 print:py-3">
      <section className="rounded-xl bg-[#f2c230] p-7 print:border print:border-black print:bg-white"><p className="text-sm font-black uppercase tracking-[.18em] text-[#b33a32] print:text-black">Today’s Mission</p><p className="mt-3 text-2xl font-extrabold leading-relaxed">Find one father carrying silent pain. Listen to his story. Help him see that change is still possible. Invite him to take one next step.</p></section>
      <div className="print-grid-one grid gap-6 lg:grid-cols-2"><Section title="Who to Look For"><Checklist items={signals}/></Section><Section title="Daily Outreach Channels"><Checklist items={channels}/></Section></div>
      <Section title="Daily Activity Target"><p className="mb-4 text-sm italic">Operating targets—not guaranteed outcomes. Fathers are people to serve, not sales quotas.</p><Checklist items={targets}/></Section>
      <Section title="Outreach Conversation Flow"><ol className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{flow.map(([title, copy], i) => <li key={title} className="rounded-lg bg-[#f8f0db] p-4 print:border print:bg-white"><span className="text-sm font-black text-[#b33a32]">{i+1}</span><h3 className="mt-1 text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-relaxed">{copy}</p></li>)}</ol></Section>
      <Section title="Opening Questions"><ul className="grid gap-3 md:grid-cols-2">{questions.map(x => <li key={x} className="rounded-lg border border-[#17231c]/15 p-4 font-semibold">“{x}”</li>)}</ul></Section>
      <Section title="Initial Outreach Messages"><div className="grid gap-4">{messages.map(([title, copy], i) => <article key={title} className="rounded-lg border border-[#17231c]/15 p-5"><h3 className="font-extrabold text-[#145b35]">Message {i+1} — {title}</h3><p className="mt-2 leading-relaxed">“{copy}”</p></article>)}</div></Section>
      <div className="print-grid-one grid gap-6 lg:grid-cols-2"><Section title="A Strong Fit"><Checklist items={strongFit}/></Section><Section title="May Not Be Ready Yet"><Checklist items={notReady}/><p className="mt-5 rounded-lg bg-[#f8f0db] p-4 text-sm font-semibold print:border print:bg-white">Do not shame these fathers. Offer truth respectfully and leave the door open.</p></Section></div>
      <Section title="Invitation Language"><blockquote className="border-l-4 border-[#f2c230] pl-5 text-lg leading-relaxed">“Based on what you shared, Papa Life may be a good next step for you. It was created specifically for fathers of adult children who want to rebuild trust, communicate more safely, and begin with the work they can control—their own. You can look at the Welcome to Papa Life page and decide whether it speaks to where you are.”</blockquote><a className="no-print mt-4 inline-flex items-center font-extrabold text-[#145b35] underline" href="/welcome-to-papa-life">Open Welcome to Papa Life</a><p className="hidden print:block">bossmobilelifecoach.com/welcome-to-papa-life</p></Section>
      <Section title="Daily Reflection"><Checklist items={reflection}/><div className="mt-5 h-28 rounded border border-[#17231c]/30" aria-label="Daily reflection notes area"/></Section>
      <Section title="Daily Scripture Focus"><div className="grid gap-4 md:grid-cols-3"><blockquote className="rounded-lg bg-[#f8f0db] p-5 print:border print:bg-white"><strong>James 1:19</strong><p className="mt-2">“Everyone should be quick to listen, slow to speak and slow to become angry.”</p></blockquote><blockquote className="rounded-lg bg-[#f8f0db] p-5 print:border print:bg-white"><strong>Luke 15:20</strong><p className="mt-2">“But while he was still a long way off, his father saw him and was filled with compassion for him.”</p></blockquote><blockquote className="rounded-lg bg-[#f8f0db] p-5 print:border print:bg-white"><strong>2 Corinthians 5:18</strong><p className="mt-2">“God…gave us the ministry of reconciliation.”</p></blockquote></div></Section>
      <Section title="Private Outreach Tracking Worksheet"><p className="mb-5 text-sm">Print this worksheet or save the page as a PDF. No personal outreach information entered here is sent to or stored by the website.</p><div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-left text-xs"><thead><tr>{["Father’s name", "Date contacted", "Channel", "Main concern", "Relationship stage", "Follow-up date", "Next action", "Notes", "Invited?", "Joined?"].map(h => <th key={h} className="border border-[#777] p-2">{h}</th>)}</tr></thead><tbody>{Array.from({length: 10}).map((_,i) => <tr key={i}>{Array.from({length: 10}).map((_,j) => <td key={j} className="h-10 border border-[#999] p-2">{j > 7 ? "□ Yes  □ No" : ""}</td>)}</tr>)}</tbody></table></div></Section>
      <p className="text-center text-sm font-semibold">Father by title. Father by presence.</p>
    </main>
  </div>;
}
